### ISSUE TITLE
It's decided

### ISSUE THREAD

**Issue by Kenseori** [lmstudio-ai/configs#39]
This program creates json files that I don't need, how can I fix it, that is, I created several of my presets, but the default ones are loaded anyway. And I only need my presets, I forbade the program to access the Internet, access to the "config-presets" folder, why does it need these presets, I don't need them, they are superfluous, I already have my personal ones, why can't I use the previous one, and not "default_lm_studio_windows.preset.json" ?
And why would you ask me about changes to the preset in a new chat, it's obvious that I don't want to change it.

**Comment by yagil** [comment]
@Kenseori thanks for the feedback, we want to make it better for you. Can you please attach screenshots of all the annoying things? Thanks!

**Comment by Kenseori** [comment]
There is no prohibit button, so it asks constantly when switching models. And when you switch the chat, the previous preset is reset.`
![S2024-04-30 1959312](https://github.com/lmstudio-ai/configs/assets/114344215/6ae0dd99-09ec-44e8-81c4-42293e67ea80)
![S2024-04-30 195922](https://github.com/lmstudio-ai/configs/assets/114344215/9cca2511-690b-4ec8-b0ca-176908b9eb33)
`

**Comment by Kenseori** [comment]
It would be great if there was a parameter to pin the preset

**Comment by Kenseori** [comment]
My fault, I didn't understand what the bottom button means, I'm sorry, the topic is closed
