### ISSUE TITLE
Please Add as Undo Option for Deleted Messages!

### ISSUE THREAD

**Issue by Iory1998** [lmstudio-ai/configs#40]
Hi, 

Thank you for your efforts. I like the app a lot. I switched from Oobabooga webui since I tried LM Studio.

However, It's missing a feature that I think is very important for someone who likes to write stories emails. 

There are moments where by mistake I delete prompts, and I have no way to restore them. 
Ctrl+Z just undoes the last text I changed, which is also annoying because If make a change to the system prompt earlier, 
and I want to undo some changes into the text of the prompt, the system prompts gets undone.

It's truly frustrating, and I urge you to add this feature ASAP.

Also, could you please add the option for spelling correction?

Thank you very much.

**Comment by yagil** [comment]
Hi @Iory1998 a few people asked for this recently and we will add it. Thanks for posting this here

**Comment by Iory1998** [comment]
Thank you for your prompt response. 
This project is great, and I wish you all good continuation.
